name: Swagger UI for OpenAPI UI
type: module
description: Provides display of OpenAPI docs using the Swagger UI plugin.
# core: 8.x
package: OpenAPI
dependencies:
  - openapi_ui:openapi_ui

# Information added by Drupal.org packaging script on 2018-07-26
version: '8.x-1.0-rc2'
core: '8.x'
project: 'openapi_ui_swagger'
datestamp: 1532563384
