name: OpenAPI
type: module
description: Connects Drupal to the OpenAPI Javascript Library
# core: 8.x
package: OpenAPI
dependencies:
  - schemata:schemata
  - schemata:schemata_json_schema

# Information added by Drupal.org packaging script on 2018-07-26
version: '8.x-1.0-beta2'
core: '8.x'
project: 'openapi'
datestamp: 1532566386
